"""
Lago Webhook Handler — receives billing events from Lago.

Events we care about:
- invoice.created: New invoice generated (end of billing period)
- invoice.finalized: Invoice ready for payment
- invoice.payment_status_updated: Payment collected/failed
- invoice.voided: Invoice cancelled

Webhook URL: POST /api/v1/webhooks/lago
Configured in Lago org settings.
"""
import logging
from fastapi import APIRouter, Request, Response

from state.postgres import db

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Lago Billing"])


@router.post("/api/v1/webhooks/lago")
async def lago_webhook(request: Request):
    """
    Receive webhook events from Lago billing.

    Lago sends JSON payloads for various billing events.
    We log them and update our local state as needed.
    """
    try:
        payload = await request.json()
    except Exception:
        logger.warning("Lago webhook: invalid JSON")
        return Response(status_code=400)

    webhook_type = payload.get("webhook_type", "unknown")
    object_type = payload.get("object_type", "unknown")

    logger.info(
        f"Lago webhook: {webhook_type} | object={object_type}",
        extra={"lago_payload": payload},
    )

    # Route by event type
    if webhook_type == "invoice.created":
        await _handle_invoice_created(payload)
    elif webhook_type == "invoice.finalized":
        await _handle_invoice_finalized(payload)
    elif webhook_type == "invoice.payment_status_updated":
        await _handle_payment_update(payload)
    elif webhook_type == "invoice.voided":
        await _handle_invoice_voided(payload)
    elif webhook_type == "customer.payment_provider_error":
        await _handle_payment_error(payload)
    else:
        logger.debug(f"Lago webhook: unhandled type {webhook_type}")

    # Always return 200 so Lago doesn't retry
    return {"status": "ok"}


async def _handle_invoice_created(payload: dict) -> None:
    """New invoice generated by Lago at end of billing period."""
    invoice = payload.get("invoice", {})
    lago_id = invoice.get("lago_id", "?")
    number = invoice.get("number", "?")
    customer = invoice.get("customer", {}).get("external_id", "?")
    total = invoice.get("total_amount_cents", 0)

    logger.info(
        f"Lago: Invoice created #{number} | customer={customer} | "
        f"total=€{total/100:.2f} | lago_id={lago_id}"
    )

    # Store reference in our billing_events table for audit
    async with db.write() as c:
        await c.execute("""
            INSERT INTO ocpp.billing_events (event_type, invoice_id, group_id, data)
            VALUES ('lago.invoice.created', $1, $2, $3::jsonb)
            ON CONFLICT DO NOTHING
        """, lago_id, customer, _safe_json(invoice))


async def _handle_invoice_finalized(payload: dict) -> None:
    """Invoice finalized — ready for payment collection."""
    invoice = payload.get("invoice", {})
    lago_id = invoice.get("lago_id", "?")
    number = invoice.get("number", "?")

    logger.info(f"Lago: Invoice finalized #{number} | lago_id={lago_id}")

    async with db.write() as c:
        await c.execute("""
            INSERT INTO ocpp.billing_events (event_type, invoice_id, group_id, data)
            VALUES ('lago.invoice.finalized', $1, $2, $3::jsonb)
            ON CONFLICT DO NOTHING
        """, lago_id,
            invoice.get("customer", {}).get("external_id", ""),
            _safe_json(invoice),
        )


async def _handle_payment_update(payload: dict) -> None:
    """Payment status changed (paid, failed, etc.)."""
    invoice = payload.get("invoice", {})
    lago_id = invoice.get("lago_id", "?")
    number = invoice.get("number", "?")
    payment_status = invoice.get("payment_status", "?")

    logger.info(
        f"Lago: Payment update #{number} | status={payment_status} | "
        f"lago_id={lago_id}"
    )

    async with db.write() as c:
        await c.execute("""
            INSERT INTO ocpp.billing_events (event_type, invoice_id, group_id, data)
            VALUES ($1, $2, $3, $4::jsonb)
            ON CONFLICT DO NOTHING
        """,
            f"lago.payment.{payment_status}",
            lago_id,
            invoice.get("customer", {}).get("external_id", ""),
            _safe_json(invoice),
        )


async def _handle_invoice_voided(payload: dict) -> None:
    """Invoice voided/cancelled."""
    invoice = payload.get("invoice", {})
    lago_id = invoice.get("lago_id", "?")
    number = invoice.get("number", "?")

    logger.info(f"Lago: Invoice voided #{number} | lago_id={lago_id}")

    async with db.write() as c:
        await c.execute("""
            INSERT INTO ocpp.billing_events (event_type, invoice_id, group_id, data)
            VALUES ('lago.invoice.voided', $1, $2, $3::jsonb)
            ON CONFLICT DO NOTHING
        """, lago_id,
            invoice.get("customer", {}).get("external_id", ""),
            _safe_json(invoice),
        )


async def _handle_payment_error(payload: dict) -> None:
    """Payment provider error."""
    customer = payload.get("customer", {})
    error = payload.get("payment_provider_error", {})

    logger.error(
        f"Lago: Payment error for {customer.get('external_id', '?')} | "
        f"code={error.get('error_code', '?')} | "
        f"message={error.get('error_message', '?')}"
    )


def _safe_json(data: dict) -> str:
    """Convert dict to JSON string for Postgres jsonb."""
    import json
    return json.dumps(data, default=str)
